FROM python:3.12-slim
WORKDIR /app

COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

COPY ./src/sindri ./sindri

ENV PYTHONPATH=/app

CMD ["fastapi", "dev", "./sindri/main.py", "--host", "0.0.0.0", "--port", "8000"]